"""
Django settings for sms project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-**n@xf$&$v^b_71o6tb^v@^s+1uo4bmsh6865awz4%=o@!s-k1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin', 
    'dal',
    'dal_select2',
       'widget_tweaks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',  
    'import_export',
    'master',
    
    'zonal_manager',
    'activity',
    'partner',
        'asm',
     
      
]
AUTH_USER_MODEL = 'account.CustomUser'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}
ROOT_URLCONF = 'sms.urls'


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_URL = '/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sms',     # Database name (same as you created in pgAdmin)
        'USER': 'postgres',           # Default PostgreSQL user
        'PASSWORD': 'Admin@123',  # Password you set during installation
        'HOST': 'localhost',          # Database host
        'PORT': '5433',               # Default PostgreSQL port
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "SMS Admin",
    "site_header": "SMS Management",
    "site_brand": "SMS Dashboard",
    "welcome_sign": "Welcome to SMS Admin Panel",
    "copyright": "© 2025 Skylink Networks",

    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://www.skylink.net.in", "new_window": True},
    ],

    "show_ui_builder": True,  # Optional design editor
}

JAZZMIN_SETTINGS.update({
    # Sidebar behavior
    "hide_apps": [],  # Optionally hide any app by name
    "hide_models": [],  # Optionally hide any model by name

    # Show apps as collapsible groups (default Django admin style)
    "navigation_expanded": False,  # ❗ Set False to collapse by default
    "order_with_respect_to": [
        "account",
        "master",
        "zonal_manager",
        "partner",
        "store",
        "support",
    ],

    # Optional custom icons per app (makes menu cleaner)
    "icons": {
        "account": "fas fa-user-circle",
        "master": "fas fa-database",
        "zonal_manager": "fas fa-chart-line",
        "partner": "fas fa-handshake",
        "store": "fas fa-store",
        "support": "fas fa-headset",
    },
})

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # optional
    "dark_mode_theme": "darkly",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "sidebar_fixed": True,
    "sidebar_nav_flat_style": False,   # ❗ Must be False
    "sidebar_nav_child_indent": True,  # ✅ Makes submenus indented
}

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent



# For development: log emails in the console
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# (for production, configure SMTP)
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "youremail@gmail.com"
# EMAIL_HOST_PASSWORD = "yourpassword"
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = "Your App <no-reply@yourapp.com>"